# Landscape2 settings
#
# This settings file allows customizing some aspects of the landscape.
#
# Reference documentation: https://github.com/cncf/landscape2/blob/main/docs/config/settings.yml

foundation: NeoNephos Foundation

url: http://localhost:8080

colors:
  color1: "rgba(15, 107, 255, 1)"
  color2: "rgba(255, 0, 170, 1)"
  color3: "rgba(96, 149, 214, 1)"
  color4: "rgba(0, 42, 81, 0.7)"
  color5: "rgba(1, 107, 204, 0.7)"
  color6: "rgba(0, 42, 81, 0.7)"
  color7: "rgba(180, 219, 255, 1)"

#featured_items:
#  - field: maturity
#    options:
#      - value: impact
#        order: 1
#        label: NeoNephos Impact
#      - value: growth
#        order: 2
#        label: NeoNephos Growth
#      - value: incubation
#        order: 3
#        label: NeoNephos Incubation
#      - value: emeritus
#        order: 4
#        label: NeoNephos Emeritus
#  - field: subcategory
#    options:
#      - value: Premium
#      - value: General

footer:
  links:
    github: "https://github.com/neonephos"
    homepage: "https://neonephos.org"
    linkedin: "https://www.linkedin.com/company/neonephos-foundation/"
    zulip: "https://slack.cncf.io/"
  logo: "https://raw.githubusercontent.com/neonephos/artwork/df8258a3e902ba98e9ceccde30d0a4e568f58319/other/neonephos_foundation/horizontal/white/neonephos_horizontal_white.svg"
  text: |
    **Copyright © Linux Foundation Europe.**
    NeoNephos is a project of Linux Foundation Europe. 
    All rights reserved. [View Policies.](https://linuxfoundation.eu/en/policies?__hstc=81619592.11739e1f4ca03192f4e918409f725053.1748961872693.1753777412155.1753863796744.19&__hssc=81619592.3.1753863796744&__hsfp=2164450451)

grid_items_size: large

groups:
  - name: Domains
    categories:
      - Federation
      - Sustainability
      - Secuirty and Compliance
      - Management
      - Application
      - Data
      - Service Orchestration
      - Cloud Edge Platform
      - Virtualization

header:
  links:
    homepage: "https://linuxfoundation.eu/"
  logo: "https://raw.githubusercontent.com/neonephos/artwork/df8258a3e902ba98e9ceccde30d0a4e568f58319/other/neonephos_foundation/horizontal/color/neonephos_horizontal_color.svg"
  hide_games: true
screenshot_width: 1500
