blank_issues_enabled: true
contact_links:
  - name: Update project or member organization information
    url: https://helpcenter.linuxfoundation.org/en/
    about: Make a request to have project or member organization information updated directly with the LF staff
